"""creates Genre model

Revision ID: 907486bc089d
Revises: 052879cd7c4c
Create Date: 2023-05-15 09:46:16.724950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907486bc089d'
down_revision = '052879cd7c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
